apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: disziplin-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/app-root: /
    nginx.ingress.kubernetes.io/configuration-snippet: |
      # Dies f채ngt 404s ab und leitet sie an index.html weiter f체r SPAs
      location / {
        try_files $uri $uri/ /index.html;
      }
spec:
  ingressClassName: nginx
  rules:
    - host: eevee
      http:
        paths:
          # Regel f체r das Backend API
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: backend-app-service
                port:
                  number: 8080

          # Regel f체r das Frontend
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-app-service
                port:
                  number: 3000